const MAIN_CONTENT ="MAIN_CONTENT";
const INTRO_SLIDES = "INTRO_SLIDE";
const AUTHENTICATION = "AUTHENTICATION";
const LOG_IN  = "LOGIN";
const SIGN_UP = "SIGNUP";
const FORGET_PASSWORD = "FORGET_PASSWORD";
const ROOT_SCENE = "ROOT_SCENE";
const REGISTRATION_ONE = 'REGISTRATION_ONE';
const REGISTRATION_TWO = "REGISTRATION_TWO";
const REGISTRATION_THREE = 'REGISTRATION_THREE';
const  COMPLETE_PROFILE = 'COMPLETE_PROFILE';
const REGISTRATION_FOUR = 'REGISTRATION_FOUR'
//added by harshal
const COURSE_REVIEW = "COURSE_REVIEW";
const BUDDIES_SCREEN = "BUDDIES_SCREEN";
const SEARCH = "SEARCH"; 


//BY HARSHIT
const MEMBERS_AREA = 'MEMBERS_AREA'
const TAG_YOUR_BUDDIES = 'TAG_YOUR_BUDDIES'
const COMMUNICATION = 'COMMUNICATION'
const ACCOUNT_DETAIL = 'ACCOUNT_DETAIL'
const MEMBERS_SECTION_PAGE2 = 'MEMBERS_SECTION_PAGE2'
const MEMBERS_SECTION_PAGE1 = 'MEMBERS_SECTION_PAGE1'
const GOLF_BAG = 'GOLF_BAG'
const PIN_ASSINGMENTS = 'PIN_ASSINGMENTS'
const HOME_COURSE_AND_SOCETIES = 'HOME_COURSE_AND_SOCETIES'
const HANDICAP_AND_STATISTICS = 'HANDICAP_AND_STATISTICS'
const MEMBERS_AREA_NEWS_FEEDS = 'MEMBERS_AREA_NEWS_FEEDS'
const CREATE_NEWS_FEED_POST = 'CREATE_NEWS_FEED_POST'
const MEMBERS_AREA_EVENTS = 'MEMBERS_AREA_EVENTS'
const MEMBERS_AREA_CREATE_EVENTS = 'MEMBERS_AREA_CREATE_EVENTS'
const MEMBERS_AREA_REQUEST_GAME = 'MEMBERS_AREA_REQUEST_GAME'
const MEMBERS_AREA_OFFER_GAME = 'MEMBERS_AREA_OFFER_GAME'
const MEMBERS_AREA_GAME_OFFERED = 'MEMBERS_AREA_GAME_OFFERED'
const MEMBERS_AREA_GAME_REQUESTED = 'MEMBERS_AREA_GAME_REQUESTED'
const MEMBERS_AREA_MARKET_PLACE = 'MEMBERS_AREA_MARKET_PLACE'
const MEMBERS_AREA_MARKET_PLACE_DRIVER = 'MEMBERS_AREA_MARKET_PLACE_DRIVER'
const MEMBERS_AREA_MARKET_PLACE_DRIVER_SELL = 'MEMBERS_AREA_MARKET_PLACE_DRIVER_SELL'
const MEMBERS_AREA_INVITE_GUESTS = 'MEMBERS_AREA_INVITE_GUESTS'
const MEMBERS_AREA_EVENTS_CREATED = 'MEMBERS_AREA_EVENTS_CREATED'
const MEMBERS_AREA_INBOX = 'MEMBERS_AREA_INBOX'
const MEMBERS_AREA_CHAT = 'MEMBERS_AREA_CHAT'
const MEMBERS_AREA_TEA_TIME = 'MEMBERS_AREA_TEA_TIME'
const MEMBERS_AREA_DINNER = 'MEMBERS_AREA_DINNER'
const CALCULATOR = 'CALCULATOR'
const COLORPICKERPAGE = 'COLORPICKERPAGE'
const ADDYOUROWNPIN = 'ADDYOUROWNPIN'
const HIGHLIGHTEDACHIVED = 'HIGHLIGHTEDACHIVED'
const ADD_ROUND_COURSE_REVIEW = 'ADD_ROUND_COURSE_REVIEW'
const VIDEOS = 'VIDEOS'
const VIDEOUPLOAD = 'VIDEOUPLOAD'
const PHOTOS = 'PHOTOS'
const SHOWVIDEOS = 'SHOWVIDEOS'
const VOICENOTES = 'VOICENOTES'
const SCORECARDEDIT = 'SCORECARDEDIT'

const CREATE_A_COMMUNITIES = 'CREATE_A_COMMUNITIES'
const EXPLORER_COMMUNITY_PRIVACY = 'EXPLORER_COMMUNITY_PRIVACY'
const EXPLORER_COMMUNITY_FIRST_PAGE = 'EXPLORER_COMMUNITY_FIRST_PAGE'
const EXPLORER_COMMUNITY_NEWS_FEEDS = 'EXPLORER_COMMUNITY_NEWS_FEEDS'
const EXPLORER_TAG_YOUR_BUDDIES = 'EXPLORER_TAG_YOUR_BUDDIES'
const EXPLORER_CREATE_NEWS_FEED_POST = 'EXPLORER_CREATE_NEWS_FEED_POST'

const PRIVACY_AND_PERMISSION ='PRIVACY_AND_PERMISSION'
const DASH_BOARD = "DASHBOARD";
const CHAT_SCREEN = "CHATSCREEN";
const EXPLORE_SCREEN = "EXPLORESCREEN";
const PROFILE_SCREEN = "PROFILESCREEN";
const OPEN_SCREEN = "OPENSCREEN";
const NEW_CHAT_SCREEN = "NEWCHATSCREEN";
const NEW_CHAT_GROUP_SCREEN = "NEWCHATGROUPSCREEN";
const HOME = 'Home';
const CONNECT = "Connect";
const EXPLORE = "Explore";
const ME = "Me";
const WALLET = "WALLET";
const FILTER = "FILTER"; 
const OPENMENU = "OpenMenu";

// suffixes
const WRAPPER_KEY_SUFFIX = 'Wrapper';
const NAVIGATOR_KEY_SUFFIX = 'Navigator';
const TABS_KEY_SUFFIX = 'Tabs';
const CONTENT_KEY_SUFFIX = 'Content';
const RESET_PASSWORD = 'ResetPassword';
const RESET_SUCCESS = "ResetSuccess";

//Chat constant(mention comments )
const CHAT = "Chat";
//this
const HANDICAP = 'HANDICAP' ;
const FEEDBACK = 'FEEDBACK';
const SETTINGS = 'SETTINGS'

//Map
const MAPCOMPONENT = "MAPCOMPONENT";
const MAP_ICONS = {

    BackImage: require('../Images/Map/PinInfoSideBar/Asset3.png'),
    SateLight :require('../Images/Map/PinInfoSideBar/Asset 15.png'),
    Marker :require('../Images/Map/PinInfoSideBar/Asset 14.png'),
    Navigation:require('../Images/Map/PinInfoSideBar/Asset 13.png'),
    ZoomIn:require('../Images/Map/PinInfoSideBar/Asset 16.png'),
    ZoomOut :require('../Images/Map/PinInfoSideBar/Asset 17.png')

};

export default {

    MAIN_CONTENT,
    AUTHENTICATION,
    LOG_IN,
    ROOT_SCENE,
    SIGN_UP,
    FORGET_PASSWORD,
    INTRO_SLIDES,
    WRAPPER_KEY_SUFFIX,
    NAVIGATOR_KEY_SUFFIX,
    TABS_KEY_SUFFIX,
    CONTENT_KEY_SUFFIX,
    REGISTRATION_ONE,
    REGISTRATION_TWO,
    REGISTRATION_THREE,
    COMPLETE_PROFILE,
    REGISTRATION_FOUR,
    RESET_PASSWORD,
    RESET_SUCCESS,

    DASH_BOARD,
    CHAT_SCREEN,
    EXPLORE_SCREEN,
    PROFILE_SCREEN,
    OPEN_SCREEN,
    NEW_CHAT_SCREEN,
    NEW_CHAT_GROUP_SCREEN,
    HOME,
    CONNECT,
    EXPLORE,
    ME,
    SEARCH,
    OPENMENU,
    CHAT,
    FEEDBACK,
    HANDICAP,
    COURSE_REVIEW,
    BUDDIES_SCREEN,
    WALLET,
    MEMBERS_AREA,
    ACCOUNT_DETAIL,
    GOLF_BAG,
    PIN_ASSINGMENTS,
    HOME_COURSE_AND_SOCETIES,
    MEMBERS_AREA_NEWS_FEEDS,
    MEMBERS_SECTION_PAGE1,
    MEMBERS_SECTION_PAGE2,
    TAG_YOUR_BUDDIES,
    CREATE_NEWS_FEED_POST,
    MEMBERS_AREA_EVENTS,
    MEMBERS_AREA_CREATE_EVENTS,
    MEMBERS_AREA_REQUEST_GAME,
    MEMBERS_AREA_GAME_REQUESTED,
    MEMBERS_AREA_GAME_OFFERED,
    MEMBERS_AREA_OFFER_GAME,
    MEMBERS_AREA_MARKET_PLACE,
    MEMBERS_AREA_MARKET_PLACE_DRIVER,
    MEMBERS_AREA_MARKET_PLACE_DRIVER_SELL,
    MEMBERS_AREA_EVENTS_CREATED,
    MEMBERS_AREA_INVITE_GUESTS,
    MEMBERS_AREA_INBOX,
    MEMBERS_AREA_CHAT,
    MEMBERS_AREA_TEA_TIME,
    MEMBERS_AREA_DINNER,
    CALCULATOR,
    ADDYOUROWNPIN,
    COLORPICKERPAGE,
    HIGHLIGHTEDACHIVED,
    ADD_ROUND_COURSE_REVIEW,
    VIDEOS,
    VIDEOUPLOAD,
    PHOTOS,
    SHOWVIDEOS,
    VOICENOTES,
    SCORECARDEDIT,

    //Communities
    CREATE_A_COMMUNITIES,
    EXPLORER_COMMUNITY_PRIVACY,
    EXPLORER_COMMUNITY_FIRST_PAGE,
    EXPLORER_COMMUNITY_NEWS_FEEDS,
    EXPLORER_CREATE_NEWS_FEED_POST,
    EXPLORER_TAG_YOUR_BUDDIES,

    SETTINGS,
    PRIVACY_AND_PERMISSION,
    HANDICAP_AND_STATISTICS,
    MAPCOMPONENT,
    MAP_ICONS,
    COMMUNICATION,
    FILTER

};


