fastlane_version "2.66.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    cocoapods
    # carthage
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"

  desc "Bundle the app"
  lane :bundle do

    bundle_command = %(cd #{ENV['PWD']} && cd .. && \
    react-native bundle \
      --dev false \
      --platform ios \
      --assets-dest ios \
      --entry-file index.ios.js \
      --bundle-output ios/main.jsbundle \
      --sourcemap-output ios/main.jsbundle.map)

    sh(bundle_command)

  end


  lane :beta do

    increment_build_number(
      xcodeproj: "./GolfPlayed.xcodeproj"
    )

    # Build a release
    gym(
      scheme: "GolfPlayed",
      clean: true,
      workspace: "./GolfPlayed.xcworkspace"
    )

    pilot
  end

  after_all do |lane|
  end

  error do |lane, exception|
  end
end
